### ISSUE TITLE
Broken pipe after syslog server restart

### ISSUE THREAD

**Issue by etricky** [mib1185/ha-addon-syslog#13]
I have the below configuration of the addon which is sending the logs to a server that has syslog-ng container. Whenever I restart the syslog-ng container I stop getting the logs from Home Assistant as it seems that the addon in not able to reconnect. If I restart the addon I can get Home Assistant logs again but I would assume that the addon should be able to reconnect on its own?

Addon configuration
```
syslog_host: 192.168.1.23
syslog_port: 514
syslog_protocol: tcp
syslog_ssl: false
syslog_ssl_verify: false
```
Addon logs after syslog server restart
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/handlers.py", line 1015, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/journal2syslog.py", line 189, in <module>
    logger.log(level=log_level, msg=msg, extra=extra)
Message: 'Call stack:'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/handlers.py", line 1015, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/journal2syslog.py", line 189, in <module>
    logger.log(level=log_level, msg=msg, extra=extra)
Message: '  File "/journal2syslog.py", line 189, in <module>'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/handlers.py", line 1015, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/journal2syslog.py", line 189, in <module>
    logger.log(level=log_level, msg=msg, extra=extra)
Message: '    logger.log(level=log_level, msg=msg, extra=extra)'
Arguments: ()

```

**Comment by mib1185** [comment]
Hi @etricky 
thanks for reaching out and reporting this issue.
I've implemented a fix, which will reconnect as soon as the syslog server is available again. Further it will also ignore an unavailable syslog server at startup of the add-on and will connect to it as soon as it is available again.

**Comment by etricky** [comment]
@mib1185 confirmed that this is fixed in the new release. Thank you so much for the quick reply and fix! 😉
