### ISSUE TITLE
Failed to load integration for translation

### ISSUE THREAD

**Issue by m4v3r1ckNl** [mib1185/ha-addon-syslog#3]
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:296
First occurred: 22:47:27 (3 occurrences)
Last logged: 22:47:27

Failed to load integration for translation: Integration 'syslog_host' not found.
Failed to load integration for translation: Integration 'syslog_port' not found.
Failed to load integration for translation: Integration 'syslog_protocol' not found.

Logger: homeassistant.setup
Source: setup.py:273
First occurred: 22:47:28 (3 occurrences)
Last logged: 22:47:28

    Setup failed for 'syslog_host': Integration not found.
    Setup failed for 'syslog_port': Integration not found.
    Setup failed for 'syslog_protocol': Integration not found.

Home Assistant - supervised
    Core 2024.4.3
    Supervisor 2024.04.0
    Operating System 12.2
    Frontend 20240404.2

**Comment by mib1185** [comment]
Hello @m4v3r1ckNl 
is there anything else in the full log? Which language do you use in HA?

**Comment by m4v3r1ckNl** [comment]
Full log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:37:22] INFO: [32mSet configuration...[0m
[08:37:22] INFO: [32mStarting the daemon...[0m

```
Logfile:

[4f0066aa_syslog_2024-04-21T06-38-26.828Z.log](https://github.com/mib1185/ha-addon-syslog/files/15050906/4f0066aa_syslog_2024-04-21T06-38-26.828Z.log)

I use English language. If you need any more info to tackle this issue, just let me know.

**Comment by mib1185** [comment]
I meant the full log of homeassistent 😁

**Comment by mib1185** [comment]
how exactly did you configure this addon? did you set anything in your `configuration.yaml` for this? if yes, that's wrong 😁

**Comment by m4v3r1ckNl** [comment]
So obviously I misread the installation requirements. Muted the code in `configuration.yaml` and rebooted my HA. Going into the syslog, it seems to be working as from 04/21.

![Screenshot 2024-04-22 at 17 11 01](https://github.com/mib1185/ha-addon-syslog/assets/26095980/eea71e4a-305a-4d21-a7f3-923a064d0bda)

edit: What is the offset in time between logging in HA and sending it to the syslog server? I'm reading -16 hours in my syslog.

Thank you for your swift reactions and directions. Much appreciated.

**Comment by mib1185** [comment]
> So obviously I misread the installation requirements. Muted the code in `configuration.yaml` and rebooted my HA. Going into the syslog, it seems to be working as from 04/21.

the configuration is done on the AddOns configuration tab in the UI, it is not intended to be added into the `configuration.yaml`

> edit: What is the offset in time between logging in HA and sending it to the syslog server? I'm reading -16 hours in my syslog.

the addon should use the time of HAOS, but maybe the timezone of HAOS is not correct passed into the addon 🤔will check this later

> Thank you for your swift reactions and directions. Much appreciated.

you're welcome :)

**Comment by mib1185** [comment]
> What is the offset in time between logging in HA and sending it to the syslog server? I'm reading -16 hours in my syslog.

where or how exactly do you see this offset? it looks like the timezone is correct passed into the addon

**Comment by m4v3r1ckNl** [comment]
Just checked the logs in Synology Logserver. The time offset is resolved, logentries are now realtime. For me this issue is now resolved. Thanks again for your support. Happy with this add-on.
