### ISSUE TITLE
Container / Addon / core indication in message

### ISSUE THREAD

**Issue by elad-bar** [mib1185/ha-addon-syslog#4]
thank you for the great addon,
one thing that makes it bit difficult to review logs is the lack of separation between components (Core vs. Addons),
according to the code, there is indication of container name, can you pls pass it as parameter within the syslog message (like prog)?

thanks

**Comment by mib1185** [comment]
Hi @elad-bar 
they should already be tagged properly, where `homeassistant` is the ha-core and everything else is its own descriptor (_the messages are RFC3164 (bsd) compliant_) - example from my logging server (_protocol center on a synology nas_)
![image](https://github.com/mib1185/ha-addon-syslog/assets/35783820/ac776307-66d1-4d3f-83a5-3c5bfd5db0f3)

**Comment by elad-bar** [comment]
thanks a lot!!!
